### ISSUE TITLE
EventStore Core Client in Normal Console app

### ISSUE THREAD

**Issue by pgermishuys** [EventStore/ClientAPI.NetCore#6] opened 2017-04-04 10:29 UTC
Initially reported by @Gentlehag
```
I created a .net standard (1.4) lib in which i write events to event store.

When I use this lib from a .net core console application everything works fine.

When I use it from a default windows console application i got this error

System.TypeInitializationException: 'The Typeinitialisor for EventStore.ClientAPI.Transport.Tcp.TcpPackageConnection" raised a exception
```
Original issue here: https://github.com/EventStore/EventStore/issues/1134

**Comment by jageall** [comment] 2017-08-11 10:13
EventStore is very cautious about taking dependencies into the main server build. Supporting both from the main build would require taking on dependencies on both the build system and the runtime we do not want to do at the moment.

**Comment by jageall** [comment] 2017-09-09 20:47
Support is moving to .net standard 2.0. I have been unable to reproduce this issue either in previous versions or the current version so I am closing this for now

**Closed** 2017-09-09 20:49 UTC
